---
- hosts: 192.168.2.15
  remote_user: "{{ansible_ssh_user}}"
  vars:
    bot_folder: "/home/{{ansible_ssh_user}}/tpa-discord-bot"
    docker_network_name: "pi"

  tasks:
    - name: Create the bot directory
      file:
        path: "{{bot_folder}}"
        owner: "{{ansible_ssh_user}}"
        state: directory
    

    # Run the Bot container
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html

    - name: Start the discord bot container
      docker_container:
        name: pingubot
        image: ghcr.io/the-penguin-army/pingubot:master
        # restart_policy: unless-stopped
        restart_retries: 3
        restart: yes
        detach: yes
        pull: yes
        env:
            TZ: "Europe/Berlin"
        volumes:
          - "{{bot_folder}}:/app/tpa-discord/data/"
        state: started
        networks:
         - name: "{{ docker_network_name }}"
        purge_networks: yes
        networks_cli_compatible: yes
        labels:
            # Exclude from Watchtower upgrades
            com.centurylinklabs.watchtower.enable: "false"
      
    # - name: Stop the Discord container
    #   docker_container:
    #     name: tpa-discord-bot
    #     state: stopped