---
- hosts: 192.168.2.15
  remote_user: "{{ansible_ssh_user}}"
  vars:
    docker_network_name: "pi"
    kuma_folder: "/home/{{ansible_ssh_user}}/kuma"

  tasks:
    - name: Create the Kuma directory
      file:
        path: "{{kuma_folder}}"
        owner: "{{ansible_ssh_user}}"
        state: directory
      become: yes

    # Run the Kuma container
    - name: Start the Kuma container
      docker_container:
        name: uptime
        image: louislam/uptime-kuma:latest
        restart_policy: unless-stopped
        restart: yes
        detach: yes
        pull: yes
        ports:
          # Syntax: Hostport : Container Port
          - "127.0.0.1:3001:3001"
        env:
          TZ: "Europe/Berlin"
        volumes:
          # User Kuma folder to container folder
          - "{{kuma_folder}}:/app/data"
        state: started
        purge_networks: yes
        networks:
         - name: "{{ docker_network_name }}"
        networks_cli_compatible: yes
        etc_hosts:
          {
            'pi.hole':'192.168.2.15'
          }