global:
  scrape_interval: 60s
scrape_configs:
  - job_name: node
    static_configs:
      - targets:
        - localhost:9100
  - job_name: vmagent
    static_configs:
      - targets:
        - localhost:8429
  - job_name: caddy
    static_configs:
      - targets:
        - localhost:80

# Debugging with
# sudo journalctl -b -u vmagent.service
